/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system_1;

import java.awt.Color;

/**
 *
 * @author shubham
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Home_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        View_Course = new javax.swing.JPanel();
        btn_viewcourse = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        btn_about = new javax.swing.JLabel();
        Edit_Cource = new javax.swing.JPanel();
        btn_editcourse = new javax.swing.JLabel();
        View_all_record = new javax.swing.JPanel();
        btn_viewallrecord = new javax.swing.JLabel();
        Search_Record = new javax.swing.JPanel();
        btn_searchrecord = new javax.swing.JLabel();
        Add_Fees = new javax.swing.JPanel();
        btn_addfees = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        View_Report = new javax.swing.JPanel();
        btn_viewreport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dr D Y Patil Institue of Engineering & Technologey,Ambi,Pune");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 940, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Savitribai Phule Pune University");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 350, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 130));

        jPanel2.setBackground(new java.awt.Color(0, 152, 152));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        View_Course.setBackground(new java.awt.Color(0, 102, 102));
        View_Course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        View_Course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                View_CourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                View_CourseMouseExited(evt);
            }
        });
        View_Course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewcourse.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_viewcourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/text-book-opened-from-top-view.png"))); // NOI18N
        btn_viewcourse.setText("  View Cource");
        btn_viewcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewcourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewcourseMouseExited(evt);
            }
        });
        View_Course.add(btn_viewcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, 340, 180));

        jPanel2.add(View_Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 370, 180));

        About.setBackground(new java.awt.Color(0, 102, 102));
        About.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
        });
        About.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_about.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_about.setForeground(new java.awt.Color(255, 255, 255));
        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/about.png"))); // NOI18N
        btn_about.setText("About");
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_aboutMouseExited(evt);
            }
        });
        About.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 60));

        jPanel2.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, 210, 60));

        Edit_Cource.setBackground(new java.awt.Color(0, 102, 102));
        Edit_Cource.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Edit_Cource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Edit_CourceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Edit_CourceMouseExited(evt);
            }
        });
        Edit_Cource.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_editcourse.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_editcourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_editcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/edit.png"))); // NOI18N
        btn_editcourse.setText("  Edit Cource");
        btn_editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseExited(evt);
            }
        });
        Edit_Cource.add(btn_editcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, 340, 180));

        jPanel2.add(Edit_Cource, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 370, 180));

        View_all_record.setBackground(new java.awt.Color(0, 102, 102));
        View_all_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        View_all_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                View_all_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                View_all_recordMouseExited(evt);
            }
        });
        View_all_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewallrecord.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_viewallrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewallrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/view all record.png"))); // NOI18N
        btn_viewallrecord.setText("View All Record");
        btn_viewallrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewallrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewallrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewallrecordMouseExited(evt);
            }
        });
        View_all_record.add(btn_viewallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 340, 180));

        jPanel2.add(View_all_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 370, 180));

        Search_Record.setBackground(new java.awt.Color(0, 102, 102));
        Search_Record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Search_Record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Search_RecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Search_RecordMouseExited(evt);
            }
        });
        Search_Record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_searchrecord.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_searchrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/search-document.png"))); // NOI18N
        btn_searchrecord.setText("  Search Record");
        btn_searchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseExited(evt);
            }
        });
        Search_Record.add(btn_searchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, 340, 180));

        jPanel2.add(Search_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 370, 180));

        Add_Fees.setBackground(new java.awt.Color(0, 102, 102));
        Add_Fees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Add_Fees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_FeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_FeesMouseExited(evt);
            }
        });
        Add_Fees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addfees.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_addfees.setForeground(new java.awt.Color(255, 255, 255));
        btn_addfees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/plus.png"))); // NOI18N
        btn_addfees.setText("Add Fees");
        btn_addfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addfeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addfeesMouseExited(evt);
            }
        });
        Add_Fees.add(btn_addfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, 340, 180));

        jPanel2.add(Add_Fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, 180));

        Logout.setBackground(new java.awt.Color(0, 102, 102));
        Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        Logout.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 60));

        jPanel2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 220, 60));

        View_Report.setBackground(new java.awt.Color(0, 102, 102));
        View_Report.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        View_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                View_ReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                View_ReportMouseExited(evt);
            }
        });
        View_Report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewreport.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btn_viewreport.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/view report.png"))); // NOI18N
        btn_viewreport.setText(" View Report");
        btn_viewreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewreportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewreportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewreportMouseExited(evt);
            }
        });
        View_Report.add(btn_viewreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 340, 180));

        jPanel2.add(View_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 370, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1300, 550));

        setSize(new java.awt.Dimension(1314, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_FeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_FeesMouseEntered
       
        
    }//GEN-LAST:event_Add_FeesMouseEntered

    private void Add_FeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_FeesMouseExited
     
        
    }//GEN-LAST:event_Add_FeesMouseExited

    private void Search_RecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_RecordMouseEntered
      
        
    }//GEN-LAST:event_Search_RecordMouseEntered

    private void Search_RecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_RecordMouseExited
        
    }//GEN-LAST:event_Search_RecordMouseExited

    private void View_all_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_all_recordMouseEntered
       
        
    }//GEN-LAST:event_View_all_recordMouseEntered

    private void View_all_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_all_recordMouseExited
       
        
    }//GEN-LAST:event_View_all_recordMouseExited

    private void Edit_CourceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_CourceMouseEntered
   
    }//GEN-LAST:event_Edit_CourceMouseEntered

    private void Edit_CourceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_CourceMouseExited
   
    }//GEN-LAST:event_Edit_CourceMouseExited

    private void View_CourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_CourseMouseEntered
        
    }//GEN-LAST:event_View_CourseMouseEntered

    private void View_CourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_CourseMouseExited
        
    }//GEN-LAST:event_View_CourseMouseExited

    private void View_ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_ReportMouseEntered
    
    }//GEN-LAST:event_View_ReportMouseEntered

    private void View_ReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_ReportMouseExited
      
    }//GEN-LAST:event_View_ReportMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
     
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        
        
    }//GEN-LAST:event_LogoutMouseExited

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
   
        
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
         
    }//GEN-LAST:event_AboutMouseExited

    private void btn_addfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addfeesMouseClicked
       AddFees addfees=new AddFees();
       addfees.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_addfeesMouseClicked

    private void btn_searchrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseClicked
          Search_Record searchRecord=new Search_Record();
          searchRecord.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btn_searchrecordMouseClicked

    private void btn_addfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addfeesMouseEntered
        Color clr=new Color(0,52,52);
        Add_Fees.setBackground(clr);
    }//GEN-LAST:event_btn_addfeesMouseEntered

    private void btn_addfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addfeesMouseExited
         Color clr=new Color(0,102,102);
        Add_Fees.setBackground(clr);
    }//GEN-LAST:event_btn_addfeesMouseExited

    private void btn_searchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseEntered
       Color clr=new Color(0,52,52);
        Search_Record.setBackground(clr);
    }//GEN-LAST:event_btn_searchrecordMouseEntered

    private void btn_searchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseExited
        Color clr=new Color(0,102,102);
        Search_Record.setBackground(clr);
    }//GEN-LAST:event_btn_searchrecordMouseExited

    private void btn_viewallrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewallrecordMouseEntered
        Color clr=new Color(0,52,52);
        View_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_viewallrecordMouseEntered

    private void btn_viewallrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewallrecordMouseExited
         Color clr=new Color(0,102,102);
        View_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_viewallrecordMouseExited

    private void btn_editcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseEntered
       Color clr=new Color(0,52,52);
        Edit_Cource.setBackground(clr);
    }//GEN-LAST:event_btn_editcourseMouseEntered

    private void btn_editcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseExited
        Color clr=new Color(0,102,102);
        Edit_Cource.setBackground(clr);
    }//GEN-LAST:event_btn_editcourseMouseExited

    private void btn_viewcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewcourseMouseEntered
        Color clr=new Color(0,52,52);
        View_Course.setBackground(clr);
    }//GEN-LAST:event_btn_viewcourseMouseEntered

    private void btn_viewcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewcourseMouseExited
       Color clr=new Color(0,102,102);
        View_Course.setBackground(clr);
    }//GEN-LAST:event_btn_viewcourseMouseExited

    private void btn_viewreportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewreportMouseEntered
       Color clr=new Color(0,52,52);
        View_Report.setBackground(clr);
    }//GEN-LAST:event_btn_viewreportMouseEntered

    private void btn_viewreportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewreportMouseExited
       Color clr=new Color(0,102,102);
        View_Report.setBackground(clr);
    }//GEN-LAST:event_btn_viewreportMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
       Color clr=new Color(0,52,52);
        Logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
         Color clr=new Color(0,102,102);
        Logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseEntered
        Color clr=new Color(0,52,52);
        About.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseEntered

    private void btn_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseExited
        Color clr=new Color(0,102,102);
        About.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseExited

    private void btn_editcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseClicked
      Edit_Course ed=new Edit_Course();
      ed.setVisible(true);
      this.dispose();
       
    }//GEN-LAST:event_btn_editcourseMouseClicked

    private void btn_viewallrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewallrecordMouseClicked
        View_All_Record var=new View_All_Record();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_viewallrecordMouseClicked

    private void btn_viewreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewreportMouseClicked
       Genrate_Report gr=new Genrate_Report();
       gr.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_viewreportMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
       System.exit(0);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseClicked
        CopyRight_Page crp=new CopyRight_Page();
        crp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_aboutMouseClicked

    private void btn_viewcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewcourseMouseClicked
        View_courses vc=new View_courses();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_viewcourseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JPanel Add_Fees;
    private javax.swing.JPanel Edit_Cource;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Search_Record;
    private javax.swing.JPanel View_Course;
    private javax.swing.JPanel View_Report;
    private javax.swing.JPanel View_all_record;
    private javax.swing.JLabel btn_about;
    private javax.swing.JLabel btn_addfees;
    private javax.swing.JLabel btn_editcourse;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_searchrecord;
    private javax.swing.JLabel btn_viewallrecord;
    private javax.swing.JLabel btn_viewcourse;
    private javax.swing.JLabel btn_viewreport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

   
}
