/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system_1;

import java.sql.*;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author shubham
 */
public class Print_Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Print_Receipt
     */
    public Print_Receipt() {
        initComponents();
        getRecord();
        Container c=getContentPane();
        c.setBackground(new Color(0,153,153));
    }
  
    public void getRecord(){
        
        try {
            Connection con=DBConnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
           ResultSet rs= pst.executeQuery();
           rs.next();
           
           txt_receiptno.setText(rs.getString("reciept_no"));
          
           txt_paymentmode.setText(rs.getString("payment_mode"));
           
           String paymentMode=rs.getString("payment_mode");
          
           if(paymentMode.equalsIgnoreCase("Cash"))
            {
             lbl_cheque_dd.setText("Cash");
             txt_cheque_dd.setText("-");
             txt_bankname.setText("-");
            }else if(paymentMode.equalsIgnoreCase("Cheque"))
            {
               lbl_cheque_dd.setText("Cheque No");
               txt_cheque_dd.setText(rs.getString("cheque_no"));
               txt_bankname.setText(rs.getString("bank_name"));   
            }else if(paymentMode.equalsIgnoreCase("DD"))
            {
               lbl_cheque_dd.setText("DD No");
               txt_cheque_dd.setText(rs.getString("dd_no"));
               txt_bankname.setText(rs.getString("bank_name"));
            }else
            {
               lbl_cheque_dd.setText("Card No");
               txt_cheque_dd.setText("-");
               txt_bankname.setText(rs.getString("bank_name"));
            }
          
           txt_recievdfrom.setText(rs.getString("student_name"));
           txt_coursename.setText(rs.getString("courses"));
           txt_date.setText(rs.getString("date"));
           txt_gstin.setText(rs.getString("gstin"));
           txt_year1.setText(rs.getString("year1"));
           txt_year2.setText(rs.getString("year2"));
           txt_initialamount.setText(rs.getString("amount"));
           txt_cgst.setText(rs.getString("cgst"));
           txt_sgst.setText(rs.getString("sgst"));
           txt_total.setText(rs.getString("total_amount"));
           txt_totalinwords.setText(rs.getString("total_in_words"));
           txt_remark.setText(rs.getString("remark"));
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panal_sidebar = new javax.swing.JPanel();
        Panal_search = new javax.swing.JPanel();
        btn_searchrecord = new javax.swing.JLabel();
        Panal_Edit_course = new javax.swing.JPanel();
        btn_Edit = new javax.swing.JLabel();
        Panal_courselist = new javax.swing.JPanel();
        btn_Courcelist = new javax.swing.JLabel();
        Panal_logout = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        Panal_home = new javax.swing.JPanel();
        btn_home = new javax.swing.JLabel();
        Panal_Allrecord = new javax.swing.JPanel();
        btn_Allrecord = new javax.swing.JLabel();
        Panal_back = new javax.swing.JPanel();
        btn_back = new javax.swing.JLabel();
        Panal_Print = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        Panal_edit = new javax.swing.JPanel();
        btn_edit = new javax.swing.JLabel();
        Panel_print = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_receiptno = new javax.swing.JLabel();
        txt_paymentmode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_recievdfrom = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txt_coursename = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        txt_sgst18 = new javax.swing.JLabel();
        txt_cgst18 = new javax.swing.JLabel();
        txt_initialamount = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txt_totalinwords = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_sgst21 = new javax.swing.JLabel();
        txt_sgst22 = new javax.swing.JLabel();
        txt_sgst23 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_remark = new javax.swing.JLabel();
        txt_sgst25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_cheque_dd = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panal_sidebar.setBackground(new java.awt.Color(0, 102, 102));
        Panal_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panal_search.setBackground(new java.awt.Color(0, 102, 102));
        Panal_search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_searchrecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_searchrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/search2.png"))); // NOI18N
        btn_searchrecord.setText(" Search Record");
        btn_searchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseExited(evt);
            }
        });
        Panal_search.add(btn_searchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 360, 60));

        Panal_Edit_course.setBackground(new java.awt.Color(0, 102, 102));
        Panal_Edit_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_Edit_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Edit.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/edit2.png"))); // NOI18N
        btn_Edit.setText(" Edit Course");
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditMouseExited(evt);
            }
        });
        Panal_Edit_course.add(btn_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_Edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 360, 60));

        Panal_courselist.setBackground(new java.awt.Color(0, 102, 102));
        Panal_courselist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_courselist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Courcelist.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_Courcelist.setForeground(new java.awt.Color(255, 255, 255));
        btn_Courcelist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/list_1.png"))); // NOI18N
        btn_Courcelist.setText(" Course List");
        btn_Courcelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CourcelistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CourcelistMouseExited(evt);
            }
        });
        Panal_courselist.add(btn_Courcelist, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_courselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 360, 60));

        Panal_logout.setBackground(new java.awt.Color(0, 102, 102));
        Panal_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        Panal_logout.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 360, 60));

        Panal_home.setBackground(new java.awt.Color(0, 102, 102));
        Panal_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/home.png"))); // NOI18N
        btn_home.setText(" Home");
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        Panal_home.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 360, 60));

        Panal_Allrecord.setBackground(new java.awt.Color(0, 102, 102));
        Panal_Allrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_Allrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Allrecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_Allrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_Allrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/view all record.png"))); // NOI18N
        btn_Allrecord.setText(" View All Record");
        btn_Allrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AllrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AllrecordMouseExited(evt);
            }
        });
        Panal_Allrecord.add(btn_Allrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 290, 60));

        Panal_sidebar.add(Panal_Allrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 360, 60));

        Panal_back.setBackground(new java.awt.Color(0, 102, 102));
        Panal_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/left-arrow.png"))); // NOI18N
        btn_back.setText(" Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        Panal_back.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 360, 60));

        Panal_Print.setBackground(new java.awt.Color(0, 102, 102));
        Panal_Print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_Print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/printer-.png"))); // NOI18N
        btn_print.setText("Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        Panal_Print.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 360, 60));

        Panal_edit.setBackground(new java.awt.Color(0, 102, 102));
        Panal_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panal_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/edit2.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        Panal_edit.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 60));

        Panal_sidebar.add(Panal_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 360, 60));

        getContentPane().add(Panal_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 690));

        Panel_print.setBackground(new java.awt.Color(255, 255, 255));
        Panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("Savitribai Phule Pune University");
        Panel_print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 260, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 102));
        jLabel9.setText("Dr D Y Patil Institue of Engineering & Technologey,Ambi,Pune");
        Panel_print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 470, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system_1/images/DYP logo.jpg"))); // NOI18N
        Panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 100));

        txt_receiptno.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_receiptno.setForeground(new java.awt.Color(51, 0, 102));
        txt_receiptno.setText("Recepit no:   ");
        Panel_print.add(txt_receiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txt_paymentmode.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_paymentmode.setForeground(new java.awt.Color(51, 0, 102));
        txt_paymentmode.setText("Payment Mode:");
        Panel_print.add(txt_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("Receipt no:    SOE");
        Panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 102));
        jLabel6.setText("Payment Mode:");
        Panel_print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        txt_bankname.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_bankname.setForeground(new java.awt.Color(51, 0, 102));
        txt_bankname.setText("Bank name:");
        Panel_print.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("The following Payment in the college office for the year:");
        Panel_print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lbl_bankname.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_bankname.setForeground(new java.awt.Color(51, 0, 102));
        lbl_bankname.setText("Bank name:");
        Panel_print.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txt_year2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(51, 0, 102));
        txt_year2.setText("2021");
        Panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        txt_recievdfrom.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_recievdfrom.setForeground(new java.awt.Color(51, 0, 102));
        txt_recievdfrom.setText("Recieved From");
        Panel_print.add(txt_recievdfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        txt_year1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(51, 0, 102));
        txt_year1.setText("2021");
        Panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 102));
        jLabel16.setText("-");
        Panel_print.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 10, -1));

        txt_gstin.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_gstin.setForeground(new java.awt.Color(51, 0, 102));
        txt_gstin.setText("GSTIN:");
        Panel_print.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 102));
        jLabel18.setText("Amount(RS)");
        Panel_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, 30));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_date.setForeground(new java.awt.Color(51, 0, 102));
        txt_date.setText("Date:");
        Panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setText("GSTIN:");
        Panel_print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 102));
        jLabel21.setText("Date:");
        Panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 102));
        Panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 750, 10));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 102));
        jLabel19.setText("Recieved From");
        Panel_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txt_coursename.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_coursename.setForeground(new java.awt.Color(51, 0, 102));
        txt_coursename.setText("Course name");
        Panel_print.add(txt_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 102));
        jLabel24.setText("Sr No");
        Panel_print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 102));
        jLabel25.setText("Head");
        Panel_print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, 30));

        txt_cgst.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_cgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_cgst.setText("CGST");
        Panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, 30));

        txt_sgst.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_sgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst.setText("SGST");
        Panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, 30));

        txt_sgst18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_sgst18.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst18.setText("SGST 9%");
        Panel_print.add(txt_sgst18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, 30));

        txt_cgst18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_cgst18.setForeground(new java.awt.Color(51, 0, 102));
        txt_cgst18.setText("CGST 9%");
        Panel_print.add(txt_cgst18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, 30));

        txt_initialamount.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_initialamount.setForeground(new java.awt.Color(51, 0, 102));
        txt_initialamount.setText("SGST");
        Panel_print.add(txt_initialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, 30));

        jSeparator3.setForeground(new java.awt.Color(51, 0, 102));
        Panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 750, 10));

        jSeparator4.setForeground(new java.awt.Color(51, 0, 102));
        Panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 210, 10));

        txt_totalinwords.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_totalinwords.setForeground(new java.awt.Color(51, 0, 102));
        txt_totalinwords.setText("Total in words");
        Panel_print.add(txt_totalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 30));

        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_total.setForeground(new java.awt.Color(51, 0, 102));
        txt_total.setText("Total");
        Panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, 30));

        txt_sgst21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_sgst21.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst21.setText("1");
        Panel_print.add(txt_sgst21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 30));

        txt_sgst22.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_sgst22.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst22.setText("Receiver Signature");
        Panel_print.add(txt_sgst22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, 30));

        txt_sgst23.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_sgst23.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst23.setText("Total in words:");
        Panel_print.add(txt_sgst23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 30));

        jSeparator5.setForeground(new java.awt.Color(51, 0, 102));
        Panel_print.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 210, 10));

        txt_remark.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_remark.setForeground(new java.awt.Color(51, 0, 102));
        txt_remark.setText("Remark:");
        Panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, 30));

        txt_sgst25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_sgst25.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst25.setText("Remark:");
        Panel_print.add(txt_sgst25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 30));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        Panel_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 760, 6));

        txt_cheque_dd.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_cheque_dd.setForeground(new java.awt.Color(51, 0, 102));
        txt_cheque_dd.setText("Cheque_dd:");
        Panel_print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        lbl_cheque_dd.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_cheque_dd.setForeground(new java.awt.Color(51, 0, 102));
        lbl_cheque_dd.setText("Cheque_dd:");
        Panel_print.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        getContentPane().add(Panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 750, 550));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Print Receipt");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        setSize(new java.awt.Dimension(1236, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseEntered
        Color clr=new Color(0,153,153);
        Panal_search.setBackground(clr);
    }//GEN-LAST:event_btn_searchrecordMouseEntered

    private void btn_searchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseExited
        Color clr=new Color(0,103,103);
        Panal_search.setBackground(clr);
    }//GEN-LAST:event_btn_searchrecordMouseExited

    private void btn_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseEntered
        Color clr=new Color(0,153,153);
        Panal_Edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_EditMouseEntered

    private void btn_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseExited
        Color clr=new Color(0,103,103);
        Panal_Edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_EditMouseExited

    private void btn_CourcelistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CourcelistMouseEntered
        Color clr=new Color(0,153,153);
        Panal_courselist.setBackground(clr);
    }//GEN-LAST:event_btn_CourcelistMouseEntered

    private void btn_CourcelistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CourcelistMouseExited
        Color clr=new Color(0,103,103);
        Panal_courselist.setBackground(clr);
    }//GEN-LAST:event_btn_CourcelistMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        Color clr=new Color(0,153,153);
        Panal_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        Color clr=new Color(0,103,103);
        Panal_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        Color clr=new Color(0,153,153);
        Panal_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        Color clr=new Color(0,103,103);
        Panal_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_AllrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AllrecordMouseEntered
        Color clr=new Color(0,153,153);
        Panal_Allrecord.setBackground(clr);
    }//GEN-LAST:event_btn_AllrecordMouseEntered

    private void btn_AllrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AllrecordMouseExited
        Color clr=new Color(0,103,103);
        Panal_Allrecord.setBackground(clr);
    }//GEN-LAST:event_btn_AllrecordMouseExited

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        Color clr=new Color(0,153,153);
        Panal_back.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        Color clr=new Color(0,103,103);
        Panal_back.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
         Color clr=new Color(0,153,153);
        Panal_Print.setBackground(clr);   
       

    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
        Color clr=new Color(0,103,103);
        Panal_Print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        Color clr=new Color(0,153,153);
        Panal_edit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        Color clr=new Color(0,103,103);
        Panal_edit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
              PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
               Panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        Update_Fees_Details update_fees=new Update_Fees_Details();
        update_fees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panal_Allrecord;
    private javax.swing.JPanel Panal_Edit_course;
    private javax.swing.JPanel Panal_Print;
    private javax.swing.JPanel Panal_back;
    private javax.swing.JPanel Panal_courselist;
    private javax.swing.JPanel Panal_edit;
    private javax.swing.JPanel Panal_home;
    private javax.swing.JPanel Panal_logout;
    private javax.swing.JPanel Panal_search;
    private javax.swing.JPanel Panal_sidebar;
    private javax.swing.JPanel Panel_print;
    private javax.swing.JLabel btn_Allrecord;
    private javax.swing.JLabel btn_Courcelist;
    private javax.swing.JLabel btn_Edit;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel btn_searchrecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cgst18;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_coursename;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialamount;
    private javax.swing.JLabel txt_paymentmode;
    private javax.swing.JLabel txt_receiptno;
    private javax.swing.JLabel txt_recievdfrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_sgst18;
    private javax.swing.JLabel txt_sgst21;
    private javax.swing.JLabel txt_sgst22;
    private javax.swing.JLabel txt_sgst23;
    private javax.swing.JLabel txt_sgst25;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalinwords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
